// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pukjkxwrqioykwscyabx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1a2preHdycWlveWt3c2N5YWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjY5ODgsImV4cCI6MjA2NDIwMjk4OH0.71JObfC5fGdcGmf3v6tAPSIhL_TEdSP14mG2JFTD0a8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);